# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MatplotlibWidget import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2451, 1843)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 2441, 1731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_app = QtWidgets.QWidget()
        self.tab_app.setObjectName("tab_app")
        self.image_show = QtWidgets.QLabel(self.tab_app)
        self.image_show.setGeometry(QtCore.QRect(989, 174, 1280, 960))
        self.image_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.image_show.setText("")
        self.image_show.setObjectName("image_show")
        self.filePath = QtWidgets.QLineEdit(self.tab_app)
        self.filePath.setGeometry(QtCore.QRect(420, 1378, 1361, 71))
        self.filePath.setObjectName("filePath")
        self.chooseFolder = QtWidgets.QPushButton(self.tab_app)
        self.chooseFolder.setGeometry(QtCore.QRect(1809, 1380, 271, 69))
        self.chooseFolder.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.chooseFolder.setObjectName("chooseFolder")
        self.fileNameLabel = QtWidgets.QLabel(self.tab_app)
        self.fileNameLabel.setGeometry(QtCore.QRect(180, 197, 159, 54))
        self.fileNameLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.fileNameText = QtWidgets.QLabel(self.tab_app)
        self.fileNameText.setGeometry(QtCore.QRect(180, 274, 591, 63))
        self.fileNameText.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.fileNameText.setText("")
        self.fileNameText.setObjectName("fileNameText")
        self.locationLabel = QtWidgets.QLabel(self.tab_app)
        self.locationLabel.setGeometry(QtCore.QRect(180, 351, 147, 54))
        self.locationLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.locationLabel.setObjectName("locationLabel")
        self.locationText = QtWidgets.QLabel(self.tab_app)
        self.locationText.setGeometry(QtCore.QRect(180, 428, 591, 63))
        self.locationText.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.locationText.setText("")
        self.locationText.setObjectName("locationText")
        self.resultLabel = QtWidgets.QLabel(self.tab_app)
        self.resultLabel.setGeometry(QtCore.QRect(180, 505, 107, 54))
        self.resultLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.resultLabel.setObjectName("resultLabel")
        self.resultText = QtWidgets.QLabel(self.tab_app)
        self.resultText.setGeometry(QtCore.QRect(180, 582, 591, 63))
        self.resultText.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.resultText.setText("")
        self.resultText.setObjectName("resultText")
        self.speedLabel = QtWidgets.QLabel(self.tab_app)
        self.speedLabel.setGeometry(QtCore.QRect(180, 659, 112, 54))
        self.speedLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.speedLabel.setObjectName("speedLabel")
        self.speedText = QtWidgets.QLabel(self.tab_app)
        self.speedText.setGeometry(QtCore.QRect(180, 736, 591, 63))
        self.speedText.setStyleSheet("font: 12pt \"Sans Serif\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.speedText.setText("")
        self.speedText.setObjectName("speedText")
        self.nextButton = QtWidgets.QPushButton(self.tab_app)
        self.nextButton.setGeometry(QtCore.QRect(180, 856, 591, 63))
        self.nextButton.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.nextButton.setObjectName("nextButton")
        self.lastButton = QtWidgets.QPushButton(self.tab_app)
        self.lastButton.setGeometry(QtCore.QRect(180, 946, 591, 63))
        self.lastButton.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.lastButton.setObjectName("lastButton")
        self.saveResult = QtWidgets.QPushButton(self.tab_app)
        self.saveResult.setGeometry(QtCore.QRect(180, 1040, 591, 63))
        self.saveResult.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.saveResult.setObjectName("saveResult")
        self.tabWidget.addTab(self.tab_app, "")
        self.tab_ft = QtWidgets.QWidget()
        self.tab_ft.setObjectName("tab_ft")
        self.log_output = QtWidgets.QTextEdit(self.tab_ft)
        self.log_output.setGeometry(QtCore.QRect(60, 1090, 2311, 571))
        self.log_output.setObjectName("log_output")
        self.detectLossView = MatplotlibWidget(self.tab_ft)
        self.detectLossView.setGeometry(QtCore.QRect(850, 40, 1521, 991))
        self.detectLossView.setObjectName("detectLossView")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_ft)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 40, 721, 991))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trainFileLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.trainFileLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.trainFileLabel.setObjectName("trainFileLabel")
        self.verticalLayout.addWidget(self.trainFileLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.trainFileEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.trainFileEdit.setObjectName("trainFileEdit")
        self.horizontalLayout.addWidget(self.trainFileEdit)
        self.chooseTrainDirButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.chooseTrainDirButton.setObjectName("chooseTrainDirButton")
        self.horizontalLayout.addWidget(self.chooseTrainDirButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pretrainCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pretrainCheckBox.setChecked(False)
        self.pretrainCheckBox.setObjectName("pretrainCheckBox")
        self.verticalLayout.addWidget(self.pretrainCheckBox)
        self.batchSizeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.batchSizeLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.batchSizeLabel.setObjectName("batchSizeLabel")
        self.verticalLayout.addWidget(self.batchSizeLabel)
        self.bnSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.bnSpinBox.setMinimum(50)
        self.bnSpinBox.setMaximum(300)
        self.bnSpinBox.setSingleStep(50)
        self.bnSpinBox.setObjectName("bnSpinBox")
        self.verticalLayout.addWidget(self.bnSpinBox)
        self.optimizationLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.optimizationLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.optimizationLabel.setObjectName("optimizationLabel")
        self.verticalLayout.addWidget(self.optimizationLabel)
        self.optComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.optComboBox.setObjectName("optComboBox")
        self.optComboBox.addItem("")
        self.optComboBox.addItem("")
        self.optComboBox.addItem("")
        self.verticalLayout.addWidget(self.optComboBox)
        self.lrLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lrLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.lrLabel.setObjectName("lrLabel")
        self.verticalLayout.addWidget(self.lrLabel)
        self.lrComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.lrComboBox.setObjectName("lrComboBox")
        self.lrComboBox.addItem("")
        self.lrComboBox.addItem("")
        self.lrComboBox.addItem("")
        self.lrComboBox.addItem("")
        self.lrComboBox.addItem("")
        self.verticalLayout.addWidget(self.lrComboBox)
        self.snapShotLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.snapShotLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.snapShotLabel.setObjectName("snapShotLabel")
        self.verticalLayout.addWidget(self.snapShotLabel)
        self.snapSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.snapSpinBox.setMinimum(5)
        self.snapSpinBox.setMaximum(100)
        self.snapSpinBox.setSingleStep(5)
        self.snapSpinBox.setProperty("value", 5)
        self.snapSpinBox.setObjectName("snapSpinBox")
        self.verticalLayout.addWidget(self.snapSpinBox)
        self.outFileLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.outFileLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.outFileLabel.setObjectName("outFileLabel")
        self.verticalLayout.addWidget(self.outFileLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outFileEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.outFileEdit.setObjectName("outFileEdit")
        self.horizontalLayout_4.addWidget(self.outFileEdit)
        self.chooseOutputFolder = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.chooseOutputFolder.setObjectName("chooseOutputFolder")
        self.horizontalLayout_4.addWidget(self.chooseOutputFolder)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.beginButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.beginButton.setObjectName("beginButton")
        self.verticalLayout.addWidget(self.beginButton)
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.tabWidget.addTab(self.tab_ft, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 30, 701, 1091))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.trainFileLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.trainFileLabel_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.trainFileLabel_2.setObjectName("trainFileLabel_2")
        self.verticalLayout_2.addWidget(self.trainFileLabel_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.trainFileEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.trainFileEdit_2.setObjectName("trainFileEdit_2")
        self.horizontalLayout_2.addWidget(self.trainFileEdit_2)
        self.chooseTrainFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chooseTrainFileButton.setObjectName("chooseTrainFileButton")
        self.horizontalLayout_2.addWidget(self.chooseTrainFileButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.testFileLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.testFileLabel.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.testFileLabel.setObjectName("testFileLabel")
        self.verticalLayout_2.addWidget(self.testFileLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.testFileEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.testFileEdit.setObjectName("testFileEdit")
        self.horizontalLayout_3.addWidget(self.testFileEdit)
        self.chooseTestFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chooseTestFileButton.setObjectName("chooseTestFileButton")
        self.horizontalLayout_3.addWidget(self.chooseTestFileButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pretrainCheckBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.pretrainCheckBox_2.setChecked(False)
        self.pretrainCheckBox_2.setObjectName("pretrainCheckBox_2")
        self.verticalLayout_2.addWidget(self.pretrainCheckBox_2)
        self.batchSizeLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.batchSizeLabel_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.batchSizeLabel_2.setObjectName("batchSizeLabel_2")
        self.verticalLayout_2.addWidget(self.batchSizeLabel_2)
        self.bnSpinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.bnSpinBox_2.setMinimum(50)
        self.bnSpinBox_2.setMaximum(300)
        self.bnSpinBox_2.setSingleStep(50)
        self.bnSpinBox_2.setObjectName("bnSpinBox_2")
        self.verticalLayout_2.addWidget(self.bnSpinBox_2)
        self.optimizationLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.optimizationLabel_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.optimizationLabel_2.setObjectName("optimizationLabel_2")
        self.verticalLayout_2.addWidget(self.optimizationLabel_2)
        self.optComboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.optComboBox_2.setObjectName("optComboBox_2")
        self.optComboBox_2.addItem("")
        self.optComboBox_2.addItem("")
        self.optComboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.optComboBox_2)
        self.lrLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lrLabel_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.lrLabel_2.setObjectName("lrLabel_2")
        self.verticalLayout_2.addWidget(self.lrLabel_2)
        self.lrComboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.lrComboBox_2.setObjectName("lrComboBox_2")
        self.lrComboBox_2.addItem("")
        self.lrComboBox_2.addItem("")
        self.lrComboBox_2.addItem("")
        self.lrComboBox_2.addItem("")
        self.lrComboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.lrComboBox_2)
        self.snapShotLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.snapShotLabel_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.snapShotLabel_2.setObjectName("snapShotLabel_2")
        self.verticalLayout_2.addWidget(self.snapShotLabel_2)
        self.snapSpinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.snapSpinBox_2.setMinimum(5)
        self.snapSpinBox_2.setMaximum(100)
        self.snapSpinBox_2.setSingleStep(5)
        self.snapSpinBox_2.setProperty("value", 5)
        self.snapSpinBox_2.setObjectName("snapSpinBox_2")
        self.verticalLayout_2.addWidget(self.snapSpinBox_2)
        self.outFileLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.outFileLabel_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.outFileLabel_2.setObjectName("outFileLabel_2")
        self.verticalLayout_2.addWidget(self.outFileLabel_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.outFileEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.outFileEdit_2.setObjectName("outFileEdit_2")
        self.horizontalLayout_5.addWidget(self.outFileEdit_2)
        self.chooseOutputFolder_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.chooseOutputFolder_2.setObjectName("chooseOutputFolder_2")
        self.horizontalLayout_5.addWidget(self.chooseOutputFolder_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.beginButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.beginButton_2.setObjectName("beginButton_2")
        self.verticalLayout_2.addWidget(self.beginButton_2)
        self.saveButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.saveButton_2.setObjectName("saveButton_2")
        self.verticalLayout_2.addWidget(self.saveButton_2)
        self.recognizetLossView = MatplotlibWidget(self.tab)
        self.recognizetLossView.setGeometry(QtCore.QRect(830, 30, 1531, 1071))
        self.recognizetLossView.setObjectName("recognizetLossView")
        self.log_output_2 = QtWidgets.QTextEdit(self.tab)
        self.log_output_2.setGeometry(QtCore.QRect(80, 1120, 2281, 541))
        self.log_output_2.setObjectName("log_output_2")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2451, 55))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actiontraining_parameters = QtWidgets.QAction(MainWindow)
        self.actiontraining_parameters.setObjectName("actiontraining_parameters")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuSettings.addAction(self.actiontraining_parameters)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseFolder.setText(_translate("MainWindow", "choose folder"))
        self.fileNameLabel.setText(_translate("MainWindow", "filename:"))
        self.locationLabel.setText(_translate("MainWindow", "location:"))
        self.resultLabel.setText(_translate("MainWindow", "result:"))
        self.speedLabel.setText(_translate("MainWindow", "speed:"))
        self.nextButton.setText(_translate("MainWindow", "next"))
        self.lastButton.setText(_translate("MainWindow", "last"))
        self.saveResult.setText(_translate("MainWindow", "save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_app), _translate("MainWindow", "application"))
        self.trainFileLabel.setText(_translate("MainWindow", "train file:"))
        self.chooseTrainDirButton.setText(_translate("MainWindow", "choose folder"))
        self.pretrainCheckBox.setText(_translate("MainWindow", "pretrained"))
        self.batchSizeLabel.setText(_translate("MainWindow", "batch size:"))
        self.optimizationLabel.setText(_translate("MainWindow", "optimization:"))
        self.optComboBox.setItemText(0, _translate("MainWindow", "Adam"))
        self.optComboBox.setItemText(1, _translate("MainWindow", "RMS"))
        self.optComboBox.setItemText(2, _translate("MainWindow", "Momentum"))
        self.lrLabel.setText(_translate("MainWindow", "learning rate:"))
        self.lrComboBox.setItemText(0, _translate("MainWindow", "0.1"))
        self.lrComboBox.setItemText(1, _translate("MainWindow", "0.01"))
        self.lrComboBox.setItemText(2, _translate("MainWindow", "0.001"))
        self.lrComboBox.setItemText(3, _translate("MainWindow", "0.0001"))
        self.lrComboBox.setItemText(4, _translate("MainWindow", "0.00001"))
        self.snapShotLabel.setText(_translate("MainWindow", "snapshot:"))
        self.outFileLabel.setText(_translate("MainWindow", "output dir:"))
        self.chooseOutputFolder.setText(_translate("MainWindow", "choose folder"))
        self.beginButton.setText(_translate("MainWindow", "begin"))
        self.saveButton.setText(_translate("MainWindow", "save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ft), _translate("MainWindow", "detection training"))
        self.trainFileLabel_2.setText(_translate("MainWindow", "train file:"))
        self.chooseTrainFileButton.setText(_translate("MainWindow", "choose file"))
        self.testFileLabel.setText(_translate("MainWindow", "test file:"))
        self.chooseTestFileButton.setText(_translate("MainWindow", "choose file"))
        self.pretrainCheckBox_2.setText(_translate("MainWindow", "pretrained"))
        self.batchSizeLabel_2.setText(_translate("MainWindow", "batch size:"))
        self.optimizationLabel_2.setText(_translate("MainWindow", "optimization:"))
        self.optComboBox_2.setItemText(0, _translate("MainWindow", "Adam"))
        self.optComboBox_2.setItemText(1, _translate("MainWindow", "RMS"))
        self.optComboBox_2.setItemText(2, _translate("MainWindow", "Momentum"))
        self.lrLabel_2.setText(_translate("MainWindow", "learning rate:"))
        self.lrComboBox_2.setItemText(0, _translate("MainWindow", "0.1"))
        self.lrComboBox_2.setItemText(1, _translate("MainWindow", "0.01"))
        self.lrComboBox_2.setItemText(2, _translate("MainWindow", "0.001"))
        self.lrComboBox_2.setItemText(3, _translate("MainWindow", "0.0001"))
        self.lrComboBox_2.setItemText(4, _translate("MainWindow", "0.00001"))
        self.snapShotLabel_2.setText(_translate("MainWindow", "snapshot:"))
        self.outFileLabel_2.setText(_translate("MainWindow", "output dir:"))
        self.chooseOutputFolder_2.setText(_translate("MainWindow", "choose folder"))
        self.beginButton_2.setText(_translate("MainWindow", "begin"))
        self.saveButton_2.setText(_translate("MainWindow", "save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "recognition training"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actiontraining_parameters.setText(_translate("MainWindow", "training parameters"))
